atomic:
  CV.cv_click:
    title: Click Image
    comment: Mouse (@{btn_type}) (@{btn_model}) image (@{input_data}) (@{click_position})
    icon: click-image
    helpManual: Search for target image in current (active) window and click this image in the window interface.
    inputList:
    - key: input_data
      title: Target Image
      tip: Support selecting image from image library to get image element
    - key: btn_type
      title: Mouse Button
      tip: ''
    - key: btn_model
      title: Click Method
      tip: ''
    - key: click_position
      title: Click Position
      tip: Select mouse click position
    - key: specified_position
      title: Specified Position
      tip: ''
    - key: horizontal_move
      title: Horizontal Translation
      tip: ''
    - key: vertical_move
      title: Vertical Translation
      tip: ''
    - key: match_similarity
      title: Match Similarity
      tip: Similarity threshold between target image and current page (maximum match accuracy is 99%). Precise match indicates that only when current interface contains target image that is completely identical can match succeed
      title: Mouse Movement Method
      tip: ''
    - key: move_speed
      title: Mouse Movement Speed
      tip: ''
    - key: wait_time
      title: Wait Time for Image (seconds)
      tip: exceedsthis timestop waiting，defaultto10Second
    outputList: []
  CV.hover_image:
    title: Mouse Hover on Image
    comment: Mouse hover on (@{click_position}) of image (@{input_data})
    icon: mouse-hover-image
    helpManual: Search for image in current (active) window and move mouse to specified position
      of this image.
    inputList:
    - key: input_data
      title: Target Image
      tip: Support selecting image from image library to get image element
    - key: click_position
      title: Hover Position
      tip: ''
    - key: specified_position
      title: Specified Position
      tip: Divide image by 9-grid layout, supports selecting any area of the 9 grids. Selected area will hover at center position of corresponding area of target image
    - key: horizontal_move
      title: Horizontal Translation
      tip: ''
    - key: vertical_move
      title: Vertical Translation
      tip: ''
    - key: match_similarity
      title: Match Similarity
      tip: Similarity threshold between target image and current page (maximum match accuracy is 99%). Precise match indicates that only when current interface contains target image that is completely identical can match succeed
    - key: move_type
      title: Mouse Movement Method
      tip: ''
    - key: move_speed
      title: Mouse Movement Speed
      tip: ''
    - key: wait_time
      title: Wait Time for Image (seconds)
      tip: exceedsthis timestop waiting，defaultto10Second
    outputList: []
  CV.is_image_exist:
    title: IF Image Exists
    comment: Judge if image (@{input_data}) (@{exist_type}) in current interface
    icon: if-image-exists
    helpManual: Search for image in current (active) window and judge whether it exists.
    inputList:
    - key: input_data
      title: Target Image
      tip: Support selecting image from image library to get image element
    - key: exist_type
      title: Judgment Type
      tip: Judge whether image exists or not exists, execute corresponding code block content respectively
    - key: match_similarity
      title: Match Similarity
      tip: Similarity threshold between target image and current page (maximum match accuracy is 99%). Precise match indicates that only when current interface contains target image that is completely identical can match succeed
    - key: wait_time
      title: Wait Time for Image (seconds)
      tip: Stop waiting if exceeds this time, default is 10 seconds
    outputList: []
  CV.wait_image:
    title: Wait for Image
    comment: Wait for image (@{input_data}) (@{wait_type})
    icon: wait-image
    helpManual: Wait for target image to appear or disappear, then continue executing process.
    inputList:
    - key: input_data
      title: Target Image
      tip: Support selecting image from image library to get image element
    - key: wait_type
      title: Wait Type
      tip: Wait for image to appear or disappear
    - key: wait_time
      title: Wait Time (seconds)
      tip: Stop waiting if exceeds this time, default is 10 seconds
    - key: match_similarity
      title: Match Similarity
      tip: Similarity threshold between target image and current page (maximum match accuracy is 99%). Precise match indicates that only when current interface contains target image that is completely identical can match succeed
    outputList:
    - key: image_wait_result
      title: Wait Result
      tip: Whether target image appears/disappears. If appears/disappears within wait time, returns true, otherwise returns false
  CV.image_input:
    title: Image Input Box Input
    comment: Click image input box (@{input_data}) and use (@{input_type}) to input (@{input_content})
    icon: image-input-box
    helpManual: Click target input box image and input content
    inputList:
    - key: input_data
      title: Target Image
      tip: Support selecting image from image library to get image element
    - key: input_type
      title: Input Method
      tip: ''
    - key: input_content
      title: Input Content
      tip: ''
    - key: simulate_flag
      title: Simulate Manual Input
      tip: ''
    - key: interval
      title: Input Interval
      tip: ''
    - key: match_similarity
      title: Match Similarity
      tip: ''
    - key: wait_time
      title: Wait Time for Image (seconds)
      tip: exceedsthis timestop waiting，defaultto10Second
    outputList: []
options:
  BtnType:
  - value: left
    label: Left Click
  - value: middle
    label: Middle Click
  - value: right
    label: Right Click
  BtnModel:
  - value: click
    label: Single Click
  - value: double_click
    label: Double Click
  PositionType:
  - value: center
    label: Center
  - value: random
    label: Random Position
  - value: specific
    label: Specified Position
  MoveType:
  - value: linear
    label: Constant Speed Linear
  - value: simulation
    label: Simulate Manual
  - value: teleportation
    label: Instant Move
  Speed:
  - value: slow
    label: Slow
  - value: normal
    label: Normal
  - value: fast
    label: Fast
  ExistType:
  - value: exist
    label: Exists
  - value: not_exist
    label: Not Exists
  WaitType:
  - value: appear
    label: Image Appears
  - value: disappear
    label: Image Disappears
  InputType:
  - value: text
    label: Character Input
  - value: clip
    label: Clipboard Input
  Simulate_flag:
  - value: 'yes'
    label: 'Yes'
  - value: 'no'
    label: 'No'
