atomic:
  Software.open:
    title: Open Program
    comment: Open application path (@{app_abs_path}), set run parameters to (@{app_args}), output result to (@{software_open})
    icon: open-program
    helpManual: ''
    inputList:
    - key: app_abs_path
      title: Application Path
      tip: Enter application file path to open
    - key: app_args
      title: Run Parameters
      tip: "Used for run parameters required by some programs, example: program environment variables"
    outputList:
    - key: software_open
      title: Application Path
      tip: Output the opened application path
  Software.close:
    title: Close Program
    comment: Close program at application path (@{app_abs_path})
    icon: close-program
    helpManual: ''
    inputList:
    - key: app_abs_path
      title: Application Path
      tip: Application path to close
    outputList: []
  Software.cmd:
    title: Cmd Command
    comment: Execute cmd command by configuring cmd string (@{cmd}), save execution result to
      (@{exec_cmd})
    icon: cmd-command
    helpManual: ''
    inputList:
    - key: cmd
      title: cmd String
      tip: Enter cmd string
    outputList:
    - key: exec_cmd
      title: Execution Result
      tip: Output custom cmd command execution result object
