atomic:
  Script.module:
    title: Run Python Module
    comment: Run Python Module(@{content:Python module})
    icon: run-python-module
    helpManual: ''
    inputList:
    - key: content
      title: Select Python Module
      tip: ''
    outputList:
    - key: program_script
      title: Execution Result
      tip: ''
options: {}
