types:
  ExcelObj:
    desc: Excel Object
    funcList:
      - key: ExcelObj.get_full_name
        funcDesc: File location
      - key: ExcelObj.get_row_count
        funcDesc: Total number of available rows
      - key: ExcelObj.get_first_free_row
        funcDesc: First available row