types:
  Date:
    desc: "Date Time"
  PATH:
    desc: "File Path"
    funcList:
      - key: "PATH.root"
        funcDesc: "Root directory"
      - key: "PATH.directory"
        funcDesc: "Parent directory"
      - key: "PATH.file_name"
        funcDesc: "File name"
      - key: "PATH.file_name_without_extension"
        funcDesc: "File name (without extension)"
      - key: "PATH.file_extension"
        funcDesc: "File extension"
  URL:
    desc: "URL"
  Pick:
    desc: "Element"
  WebPick:
    desc: "Web Element"
  WinPick:
    desc: "Windows Element"
  FeishuBaseInstance:
    desc: "Feishu Object"
  DialogResult:
    desc: "Dialog Output Result"
options:
  bool:
    - value: "True"
      label: "Yes"
    - value: "False"
      label: "No"
  Bool:
    - value: "True"
      label: "Yes"
    - value: "False"
      label: "No"