atomic:
  WinEle.click_element:
    title: Click Element (Desktop)
    comment: '@{click_type} the picked element @{pick}, wait up to @{wait_time} seconds until this element appears'
    icon: click-element-win
    helpManual: ''
    inputList:
    - key: pick
      title: Element Picker
      tip: ''
    - key: click_button
      title: Click Button
      tip: ''
    - key: click_type
      title: Click Type
      tip: ''
    - key: wait_time
      title: Wait for Element to Appear
      tip: ''
    - key: horizontals_offset
      title: Horizontal Offset
      tip: ''
    - key: verticals_offset
      title: Vertical Offset
      tip: ''
    - key: keyboard_input
      title: Keyboard Assist Input
      tip: Press certain keys on the keyboard while clicking
    outputList: []
  WinEle.screenshot_element:
    title: Element Screenshot (Desktop)
    comment: Screenshot the picked element @{pick} and save to folder @{file_path}
    icon: element-screenshot-win
    helpManual: ''
    inputList:
    - key: pick
      title: Element Picker
      tip: ''
    - key: file_path
      title: File Save Path
      tip: ''
    - key: file_name
      title: File Name
      tip: ''
    - key: exist_type
      title: Action When File Exists
      tip: ''
    outputList: []
  WinEle.hover_element:
    title: Hover Element (Desktop)
    comment: Hover mouse over the picked element @{pick} and set wait time @{wait_time} seconds
    icon: mouse-hover-element-win
    helpManual: ''
    inputList:
    - key: pick
      title: Element Picker
      tip: ''
    - key: wait_time
      title: Wait for Element to Appear
      tip: ''
    outputList: []
  WinEle.input_text_element:
    title: Fill Input Field (Desktop)
    comment: Fill input field @{pick}, set input type to @{input_type}, input content is @{text}
    icon: fill-input-win
    helpManual: ''
    inputList:
    - key: pick
      title: Element Picker
      tip: ''
    - key: input_type
      title: Input Type
      tip: ''
    - key: text
      title: Input Content
      tip: ''
    - key: clear_first
      title: Clear Input Field Content
      tip: ''
    - key: wait_time
      title: Wait for Element to Appear
      tip: ''
    outputList: []
  WinEle.get_element_text:
    title: Get Element Text (Desktop)
    comment: Extract text from element @{pick} and save to @{ele_text}
    icon: get-element-text-win
    helpManual: ''
    inputList:
    - key: pick
      title: Element Picker
      tip: ''
    - key: wait_time
      title: Wait for Element to Appear
      tip: ''
    outputList:
    - key: ele_text
      title: Element Text
      tip: ''
  WinEle.similar:
    title: Get Similar Elements List (Desktop)
    comment: Get elements similar to the picked element @{pick}, and output the similar elements array to @{get_similar_ele}
    icon: get-similar-elements-win
    helpManual: ''
    inputList:
    - key: pick
      title: Similar Element Picker
      tip: Pick two similar elements at different positions on the desktop
    - key: wait_time
      title: Wait for Element to Appear (seconds)
      tip: Stop waiting after this time
    outputList:
    - key: get_similar_ele
      title: Element Information
      tip: ''
options:
  MouseClickButton:
  - value: left
    label: Left Button
  - value: right
    label: Right Button
  - value: middle
    label: Middle Button
  MouseClickType:
  - value: click
    label: Single Click
  - value: double_click
    label: Double Click
  MouseClickKeyboard:
  - value: none
    label: Not Used
  - value: alt
    label: Alt Key
  - value: ctrl
    label: Ctrl Key
  - value: shift
    label: Shift Key
  - value: win
    label: Win Key
  FileExistenceType:
  - value: overwrite
    label: Overwrite Existing File
  - value: rename
    label: Create File Copy
  - value: cancel
    label: Cancel Save Operation
  ElementInputType:
  - value: keyboard
    label: Keyboard Input
  - value: clipboard
    label: Clipboard Input
  Bool:
  - value: true
    label: Yes
  - value: false
    label: No
