types:
  Browser:
    desc: Browser Object
    funcList:
      - key: Browser.get_url
        funcDesc: The URL of this webpage
      - key: Browser.get_title
        funcDesc: The title of this webpage