atomic:
  PDF.get_pages_num:
    title: Get PDF Document Page Count
    comment: Get page count of PDF document at @{file_path}, return @{pdf_pages_num}
    icon: pdf-get-page-count
    helpManual: ''
    inputList:
    - key: file_path
      title: PDF File Path
      tip: Enter PDF file path
    - key: password
      title: PDF File Password
      tip: Enter PDF file password, leave empty if no password
    outputList:
    - key: pdf_pages_num
      title: PDF Document Page Count
      tip: Returns PDF document page count
  PDF.get_pdf_text:
    title: Extract PDF Document Text
    comment: Extract text from PDF document at @{file_path}, return as string or list @{pdf_text}
    icon: pdf-extract-text
    helpManual: ''
    inputList:
    - key: file_path
      title: PDF File Path
      tip: Enter PDF file path
    - key: password
      title: PDF File Password
      tip: Enter PDF file password, leave empty if no password
    - key: select_range
      title: Select Range
      tip: Select range, supports all pages or specified page range
    - key: page_range
      title: Specified Page Range
      tip: Enter page range, format is 1-3,5,7-9,11, meaning pages 1 to 3, page 5, pages 7 to 9, page 11
    - key: text_save_type
      title: Save as File
      tip: Choose whether to save extracted text as file, can save as Word or text file format
    - key: save_dir
      title: Save File Path
      tip: Select the folder path to save the file
    - key: save_file_name
      title: Save File Name
      tip: Enter save file name, if not entered, default file name will be used
    - key: exist_handle_type
      title: Existing File Handling
      tip: Select how to handle existing files, supports overwrite original file, create file copy, or cancel save operation
    outputList:
    - key: pdf_text
      title: Extracted PDF Document Text
      tip: Extracted PDF document text, stored and returned as a list
  PDF.get_pdf_images:
    title: Extract PDF Document Images
    comment: Extract images from PDF document at @{file_path}, and save to @{save_dir} folder
    icon: pdf-extract-images
    helpManual: ''
    inputList:
    - key: file_path
      title: PDF File Path
      tip: ''
    - key: pwd
      title: PDF File Password
      tip: If PDF file requires password, please enter password, otherwise leave empty
    - key: select_range
      title: Select Range
      tip: Select range, supports all pages or specified page range
    - key: page_range
      title: Specified Page Range
      tip: Enter page range, format is 1-3,5,7-9,11, meaning pages 1 to 3, page 5, pages 7 to 9, page 11
    - key: image_type
      title: Image Format
      tip: Select image format, supports JPEG, PNG and other formats
    - key: save_dir
      title: Save File Path
      tip: Select the folder path to save the file
    - key: prefix
      title: Image File Name Prefix
      tip: Enter image file name prefix, if not entered, original file name prefix will be used
    - key: exist_handle_type
      title: Existing File Handling
      tip: Select how to handle existing files, supports overwrite original file, create file copy, or cancel save operation
    outputList: []
  PDF.merge_pdf_files:
    title: Merge PDF Files
    comment: Merge PDF files into one PDF file, and save to @{pdf_merge_file_path} path
    icon: merge-pdf-files
    helpManual: ''
    inputList:
    - key: merge_type
      title: Merge Method
      tip: Select merge method, supports merge by folder or merge by file
    - key: file_folder_path
      title: Merge Folder
      tip: Will merge all PDF files in the folder
    - key: files_path
      title: Merge Files
      tip: Will merge all selected PDF files
    - key: save_dir
      title: Save File Path
      tip: Select the folder path to save the file
    - key: new_file_name
      title: Merged File Name
      tip: Enter merged file name, if not entered, default file name will be used
    - key: new_pwd_flag
      title: Set Password for New PDF File
      tip: Choose whether to set password
    - key: new_pwd
      title: New PDF File Password
      tip: Enter new PDF file password
    - key: exist_handle_type
      title: Existing File Handling
      tip: Select how to handle existing files, supports overwrite original file, create file copy, or cancel save operation
    outputList:
    - key: pdf_merge_file_path
      title: Merged PDF File Path
      tip: Merged PDF file path
  PDF.extract_pdf_file:
    title: Extract PDF Specified Pages
    comment: Extract specified pages from PDF document at @{file_path}, and save to @{extract_file_path} folder
    icon: pdf-extract-page
    helpManual: ''
    inputList:
    - key: file_path
      title: PDF File Path
      tip: Select the PDF file path to extract
    - key: pwd
      title: PDF File Password
      tip: If PDF file requires password, please enter password, otherwise leave empty
    - key: page_range
      title: Specified Page Range
      tip: Enter page range, format is 1-3,5,7-9,11, meaning pages 1 to 3, page 5, pages 7 to 9, page 11
    - key: save_dir
      title: Save File Path
      tip: Select the folder path to save the file
    - key: new_file_name
      title: Extracted New PDF File Name
      tip: Enter new file name, if not entered, default file name will be used
    - key: new_pwd_flag
      title: Set Password for New PDF File
      tip: Choose whether to set password
    - key: new_pwd
      title: New PDF File Password
      tip: Enter new PDF file password
    - key: exist_handle_type
      title: Existing File Handling
      tip: Select how to handle existing files, supports overwrite original file, create file copy, or cancel save operation
    outputList:
    - key: extract_file_path
      title: Extracted PDF File Path
      tip: Extracted PDF file path
  PDF.extract_forms_from_pdf:
    title: Extract PDF Table to Excel
    comment: Extract tables from PDF document at @{file_path}, and save to @{forms_file_path} folder
    icon: pdf-extract-table-to-excel
    helpManual: ''
    inputList:
    - key: file_path
      title: PDF File Path
      tip: Select the PDF file path to extract tables
    - key: pwd
      title: PDF File Password
      tip: If PDF file requires password, please enter password, otherwise leave empty
    - key: select_range
      title: Select Range
      tip: Select range, supports all pages or specified page range
    - key: page_range
      title: Specified Page Range
      tip: Enter page range, format is 1-3,5,7-9,11, meaning pages 1 to 3, page 5, pages 7 to 9, page 11
    - key: combine_flag
      title: Merge Multiple Tables
      tip: When cross-page tables appear, you can choose whether to merge into one table, it is recommended to choose merge when headers are the same
    - key: save_dir
      title: Save File Path
      tip: Select the folder path to save the file
    - key: new_file_name
      title: Table File Name
      tip: Enter table file name, if not entered, default file name will be used
    - key: exist_handle_type
      title: Existing File Handling
      tip: Select how to handle existing files, supports overwrite original file, create file copy, or cancel save operation
    outputList:
    - key: forms_file_path
      title: Extracted Excel File Path
      tip: Extracted Excel file path
  PDF.convert_pdf_to_img:
    title: PDF Page to Image
    comment: Convert PDF document at @{file_path} to images, and save to @{save_dir} folder
    icon: pdf-page-to-image
    helpManual: ''
    inputList:
    - key: file_path
      title: PDF File Path
      tip: Select the PDF file path to convert
    - key: pwd
      title: PDF File Password
      tip: If PDF file requires password, please enter password, otherwise leave empty
    - key: image_type
      title: Image Format
      tip: Select image format, supports JPEG, PNG and other formats
    - key: select_range
      title: Select Range
      tip: Select range, supports all pages or specified page range
    - key: page_range
      title: Specified Page Range
      tip: Enter page range, format is 1-3,5,7-9,11, meaning pages 1 to 3, page 5, pages 7 to 9, page 11
    - key: save_dir
      title: Save File Path
      tip: Select the folder path to save the file
    - key: prefix
      title: Image File Name Prefix
      tip: Enter image file name prefix, if not entered, original file name prefix will be used
    - key: exist_handle_type
      title: Existing File Handling
      tip: Select how to handle existing files, supports overwrite original file, create file copy, or cancel save operation
    outputList: []
options:
  PictureType:
  - value: png
    label: PNG
  - value: jpeg
    label: JPEG
  SelectRangeType:
  - value: all
    label: All Pages
  - value: part
    label: Specified Pages
  FileExistenceType:
  - value: overwrite
    label: Overwrite Existing File
  - value: rename
    label: Create File Copy
  - value: cancel
    label: Cancel Save Operation
  MergeType:
  - value: folder
    label: Merge by Folder
  - value: file
    label: Merge by File
  TextSaveType:
  - value: word
    label: Word File
  - value: txt
    label: Text File
  - value: word_and_txt
    label: Word File and Text File
  - value: none
    label: Don't Save
