atomic:
  VerifyCode.picture_code:
    title: General Text Captcha
    comment: Recognize captcha @{picture_pick} in browser, return recognition result
      @{code_result}
    icon: captcha-text
    helpManual: ''
    inputList:
    - key: browser_obj
      title: Browser Object
      tip: ''
    - key: picture_pick
      title: Pick Captcha Object
      tip: ''
    - key: code_type
      title: Captcha Type
      tip: ''
    - key: input_flag
      title: Fill Input Box
      tip: ''
    - key: input_box
      title: Input Box Object
      tip: ''
    outputList:
    - key: code_result
      title: Recognition Result
      tip: ''
  VerifyCode.slider_code:
    title: General Slider Captcha
    comment: On background image @{picture_pick} slider captcha, drag slider @{slider_pick}
      to specified position, drag distance @{drag_distance}
    icon: captcha-slider
    helpManual: ''
    inputList:
    - key: browser_obj
      title: Browser Object
      tip: ''
    - key: picture_pick
      title: Background Image Object
      tip: ''
    - key: slider_pick
      title: Pick Slider Object
      tip: ''
    - key: unmatched_flag
      title: Is Variable Speed Captcha
      tip: ''
    - key: move_pic_pick
      title: Pick Sliding Image Object
      tip: ''
    - key: mini_step
      title: Fine Adjustment Step (px)
      tip: ''
    outputList:
    - key: drag_distance
      title: Move Distance
      tip: ''
  VerifyCode.click_code:
    title: General Click Captcha
    comment: On background image @{picture_pick} click captcha, click corresponding position
    icon: captcha-click
    helpManual: ''
    inputList:
    - key: browser_obj
      title: Browser Object
      tip: ''
    - key: picture_pick
      title: Click Image Object
      tip: Need to include large click image and small image indicating order
    - key: hint_position
      title: Position of Order Indicator Image Relative to Main Image
      tip: If the image indicating order is at the bottom relative to the main image, select bottom, otherwise select top
options:
  PictureCodeType:
  - value: '10110'
    label: General Text Captcha 1-4 digits
  - value: '10111'
    label: General Text Captcha 5-8 digits
  - value: '10211'
    label: General Text Captcha (Special)
  Bool:
  - value: true
    label: 'Yes'
  - value: false
    label: 'No'
  HintPosition:
  - value: bottom
    label: Bottom
  - value: top
    label: Top
