atomic:
  Window.exist:
    title: IF Window Exists
    comment: Check if the picked window (@{pick}) @{check_type}, if true execute the following operations
    icon: check-window-exists
    helpManual: ''
    inputList:
    - key: pick
      title: Window Picker
      tip: Select the window object to check for existence
    - key: check_type
      title: Check Type
      tip: Select the check type, default is exists
    - key: wait_time
      title: Wait Time (seconds)
      tip: Time to wait for the check result
    outputList: []
  Window.top:
    title: Pin Window
    comment: Pin window object (@{pick})
    icon: pin-window
    helpManual: ''
    inputList:
    - key: pick
      title: Window Picker
      tip: Pick the window object to pin on top
    outputList: []
  Window.close:
    title: Close Window
    comment: Close desktop application window object (@{pick})
    icon: close-window
    helpManual: ''
    inputList:
    - key: pick
      title: Window Picker
      tip: Pick the window object to close
    outputList: []
  Window.set_size:
    title: Resize Window
    comment: Resize the picked window (@{pick}), set the window width and height to (@{width}) (@{height}) using (@{size_type:Custom}) method
    icon: resize-window
    helpManual: ''
    inputList:
    - key: pick
      title: Window Picker
      tip: Pick the desktop application window to resize
    - key: size_type
      title: Resize Method
      tip: ''
    - key: width
      title: Window Width
      tip: Set the specified window width value in screen resolution pixels (px), typically a value between 0-9999
    - key: height
      title: Window Height
      tip: Set the specified window height value in screen resolution pixels (px), typically a value between 0-9999
    outputList: []
options:
  WindowExistType:
  - value: exist
    label: Exists
  - value: not_exist
    label: Does Not Exist
  WindowSizeType:
  - value: custom
    label: Custom
  - value: max
    label: Maximize
  - value: min
    label: Minimize
