atomic:
  Report.print:
    title: Log Print
    comment: Print variable (@{msg})
    icon: log-print
    helpManual: ''
    inputList:
    - key: report_type
      title: Log Type
    - key: msg
      title: Log Content
      tip: Print stream variables output during execution
    outputList: null
options:
  ReportLevelType:
  - value: debug
    label: Debug
  - value: info
    label: Info
  - value: warning
    label: Warning
  - value: error
    label: Error
