atomic:
  Email.send_email:
    title: Send Email
    comment: Send email to specified mailbox @{receiver}
    icon: send-email
    helpManual: ''
    inputList:
    - key: receiver
      title: Recipient Email
      tip: ''
    - key: cc
      title: CC Email
      tip: ''
    - key: subject
      title: Subject
      tip: ''
    - key: is_html
      title: Is HTML Format
      tip: ''
    - key: content
      title: Content
      tip: ''
    - key: attachment_path
      title: Attachment Path
      tip: ''
    - key: mail_server
      title: Mail Server
      tip: ''
    - key: other_mail_server
      title: Other Mail Server
      tip: ''
    - key: mail_port
      title: Mail Server Port
      tip: ''
    - key: use_ssl
      title: Use SSL Encryption
      tip: ''
    - key: sender_mail
      title: Sender Email
      tip: ''
    - key: send_name
      title: Sender Name
      tip: ''
    - key: password
      title: Password/Authorization Code
      tip: ''
    - key: bcc
      title: BCC Email
      tip: ''
    - key: replace_table
      title: Smart Fill Table
      tip: ''
    outputList: []
  Email.receive_email:
    title: Receive Email
    comment: Receive email info from mailbox (@{user_mail})
    icon: receive-email
    helpManual: ''
    inputList:
    - key: mail_server
      title: Mail Server Address
      tip: Select a mailbox type
    - key: custom_mail_server
      title: IMAP Server Address
      tip: Enter specified IMAP server address
    - key: custom_mail_port
      title: IMAP Server Port
      tip: Enter specified IMAP server port
    - key: user_mail
      title: User Email Account
      tip: IMAP server authentication username, usually the mailbox account, refer to specific email service provider specifications
    - key: user_password
      title: Authorization Code
      tip: IMAP server authentication authorization code, usually requires SMS verification to activate. Some mailboxes use account password. Refer to specific email service provider specifications
    - key: max_return_num
      title: Maximum Email Count
      tip: Maximum number of emails to return
    - key: unseen_flag
      title: Unread Only
      tip: Get only unread emails or all emails
    - key: save_attachment_flag
      title: Save Attachments
      tip: Whether to download email attachments
    - key: save_attachment_path
      title: Save Directory
      tip: Attachment save directory
    - key: folder_name
      title: Folder Name
      tip: Enter the mailbox folder name to receive emails from, default is INBOX
    - key: mask_as_read_flag
      title: Mark as Read
      tip: After receiving email, mark email as read
    - key: sender_text
      title: Sender Contains
      tip: Filter by sender containing keywords
    - key: receiver_text
      title: Recipient Contains
      tip: Filter by recipient containing keywords
    - key: theme_text
      title: Subject Contains
      tip: Filter by subject containing keywords
    - key: content_text
      title: Body Contains
      tip: Filter by body containing keywords
    outputList:
    - key: mail_list
      title: Save Email List
      tip: Specify a variable name to store the returned email list to this variable
options:
  Bool:
  - value: true
    label: 'Yes'
  - value: false
    label: 'No'
  EmailServerType:
  - value: other
    label: Other Mailbox
  - value: '126'
    label: '126'
  - value: '163'
    label: '163'
  - value: qq
    label: QQ
  - value: iflytek
    label: iFlytek Mailbox
