atomic:
  Encrypt.md5_encrypt:
    title: MD5 Encryption
    comment: Perform MD5 encryption on string (@{source_str})
    icon: md5-encrypt
    helpManual: ''
    inputList:
    - key: source_str
      title: String to Encrypt
      tip: ''
    - key: md5_method
      title: Encryption Bits
      tip: ''
    - key: case_method
      title: Case Selection
      tip: ''
    outputList:
    - key: md5_encrypted_result
      title: MD5 Encryption Result
      tip: ''
  Encrypt.sha_encrypt:
    title: SHA Encryption
    comment: Perform SHA encryption on string (@{source_str})
    icon: sha-encrypt
    helpManual: ''
    inputList:
    - key: source_str
      title: String to Encrypt
      tip: ''
    - key: sha_method
      title: SHA Encryption Method
      tip: ''
    - key: case_method
      title: Case Selection
      tip: ''
    outputList:
    - key: sha_encrypted_result
      title: SHA Encryption Result
      tip: ''
  Encrypt.symmetric_encrypt:
    title: Symmetric Encryption
    comment: Perform symmetric encryption on string (@{source_str})
    icon: symmetric-encrypt
    helpManual: ''
    inputList:
    - key: source_str
      title: String to Encrypt
      tip: ''
    - key: password
      title: Encryption Key
      tip: ''
    outputList:
    - key: symmetric_encrypted_result
      title: Symmetric Encryption Result
      tip: ''
  Encrypt.symmetric_decrypt:
    title: Symmetric Decryption
    comment: Perform symmetric decryption on string (@{source_str})
    icon: symmetric-decrypt
    helpManual: ''
    inputList:
    - key: source_str
      title: String to Decrypt
      tip: ''
    - key: password
      title: Decryption Key
      tip: ''
    outputList:
    - key: symmetric_decrypted_result
      title: Symmetric Decryption Result
      tip: ''
  Encrypt.base64_encoding:
    title: Base64 Encoding
    comment: Read string or image file and encode to Base64 string, return encoded string (@{encoded_string})
    icon: base64-encode
    helpManual: ''
    inputList:
    - key: encode_type
      title: Encoding Type
      tip: ''
    - key: string_data
      title: String Data
      tip: ''
    - key: file_path
      title: File Path
      tip: ''
    outputList:
    - key: encoded_string
      title: Encoded String
      tip: ''
  Encrypt.base64_decoding:
    title: Base64 Decoding
    comment: Read Base64 string (@{string_data}), decode to string or image file
    icon: base64-decode
    helpManual: ''
    inputList:
    - key: decode_type
      title: Decoding Type
      tip: ''
    - key: string_data
      title: Base64 String
      tip: ''
    - key: file_path
      title: Image Save Folder
      tip: ''
    - key: file_name
      title: Image File Name
      tip: ''
    - key: exist_handle_type
      title: Handling for Existing Files
      tip: Select handling method for existing files, supports overwrite original file, create file copy, or cancel save operation
    outputList:
    - key: decoded_string
      title: Decoded String/Image Absolute Path
      tip: ''
options:
  MD5bitsType:
  - value: '32'
    label: 32-bit
  - value: '16'
    label: 16-bit
  EncryptCaseType:
  - value: lower
    label: Lowercase
  - value: upper
    label: Uppercase
  SHAType:
  - value: sha1
    label: sha1
  - value: sha224
    label: sha224
  - value: sha256
    label: sha256
  - value: sha384
    label: sha384
  - value: sha512
    label: sha512
  - value: sha3_224
    label: sha3_224
  - value: sha3_256
    label: sha3_256
  - value: sha3_384
    label: sha3_384
  - value: sha3_512
    label: sha3_512
  Base64CodeType:
  - value: string
    label: String
  - value: picture
    label: image
  FileExistenceType:
  - value: overwrite
    label: Overwrite Original File
  - value: rename
    label: Create File Copy
  - value: cancel
    label: Cancel Save Operation
