atomic:
  Network.http_request:
    title: HTTP Request
    comment: Send HTTP request (@{request_type}) to URL(@{url}), request headers(@{headers}), request body(@{body}), and save response result to {@{http_response}}
    icon: http-request
    helpManual: Send HTTP request to specified URL
    inputList:
    - key: url
      title: URL
      tip: ''
    - key: request_type
      title: Request Type
      tip: ''
    - key: headers
      title: Request Headers
      tip: ''
    - key: body
      title: Request Body
      tip: ''
    - key: file_path
      title: File Path to Upload
      tip: ''
    - key: time_out
      title: Timeout
      tip: ''
    - key: save_type
      title: Save Response Result to File
      tip: Save response result to specified text file
    - key: save_path
      title: Document Save Directory
      tip: Enter file save directory
    - key: save_name
      title: File Name
      tip: Enter save file name, default is text file
    outputList:
    - key: http_response
      title: Save Response Result to
      tip: ''
  Network.http_download:
    title: HTTP Download
    comment: HTTP Download
    icon: http-download
    helpManual: Download file from specified URL(@{url}) and save to specified directory(@{dst_dir}), and save download path to variable(@{http_download_path})
    inputList:
    - key: url
      title: Download URL
      tip: ''
    - key: dst_dir
      title: File Save Directory
      tip: ''
    - key: rename
      title: Specify File Name
      tip: If not specified, automatically uses default file name from download path, reports error if no default file name
    - key: state_type
      title: When Directory Does Not Exist
      tip: Set handling method when file save directory does not exist
    - key: exist_type
      title: When File Exists
      tip: Set handling method when target file already exists
    outputList:
    - key: http_download_path
      title: Save Downloaded File to
      tip: Save downloaded file path to variable
  Network.ftp_create:
    title: Create FTP Connection
    comment: Establish FTP connection to address(@{host}), port(@{port}), output as(@{ftp_instance})
    icon: ftp-create-connection
    helpManual: Establish an FTP connection to file server and return connection object
    inputList:
    - key: host
      title: Server Address
      tip: FTP server address
    - key: port
      title: Server Port Number
      tip: FTP server port number
    - key: name
      title: Username
      tip: Login account provided by file server
    - key: password
      title: User Password
      tip: Password for login account provided by file server
    outputList:
    - key: ftp_instance
      title: Save FTP Connection Object to
      tip: Save created FTP connection object to specified variable
  Network.ftp_close:
    title: Close FTP Connection
    comment: Disconnect FTP connection(@{ftp_instance}), and output result to variable(@{close_ftp})
    icon: ftp-close-connection
    helpManual: Disconnect an FTP connection and return disconnect result
    inputList:
    - key: ftp_instance
      title: FTP Object
      tip: FTP connection object to disconnect
    outputList:
    - key: close_ftp
      title: Save Disconnect Result to
      tip: Boolean value of whether FTP connection was successfully disconnected
  Network.get_work_dir:
    title: Get Working Directory (FTP)
    comment: Get current working directory of(@{ftp_instance}), output as(@{get_work_dir})
    icon: get-work-directory
    helpManual: Get current working directory of FTP object
    inputList:
    - key: ftp_instance
      title: FTP Connection Object
      tip: Current FTP connection object
    outputList:
    - key: get_work_dir
      title: Save Working Directory to
      tip: Output obtained working directory
  Network.change_working_dir:
    title: Change Working Directory (FTP)
    comment: Change working directory of FTP connection(@{ftp_instance}) to(@{new_work_dir}), and save changed working directory to(@{change_work_dir})
    icon: change-work-directory
    helpManual: Change FTP connection current working directory to specified path
    inputList:
    - key: ftp_instance
      title: FTP Connection Object
      tip: FTP connection object that needs working directory change
    - key: new_work_dir
      title: Working Directory
      tip: New working directory to change to
    outputList:
    - key: change_work_dir
      title: Changed Working Directory
      tip: Output current working directory after change
  Network.create_folder:
    title: Create Folder (FTP)
    comment: Create folder(@{folder_name}) under specified FTP connection(@{ftp_instance}), and save new folder path to(@{new_folder})
    icon: create-folder
    helpManual: Create folder under specified FTP connection
    inputList:
    - key: ftp_instance
      title: FTP Connection Object
      tip: FTP connection object where folder needs to be created
    - key: folder_name
      title: New Folder Name
      tip: Folder name to create
    - key: exist_type
      title: When Folder Exists
      tip: Operation to perform when folder with same name exists under FTP connection
    outputList:
    - key: new_folder
      title: Created Folder Path
      tip: Save created folder path to variable
  Network.get_ftp_list:
    title: Get File/Folder (FTP)
    comment: Get (@{file_type}) list under specified FTP connection(@{ftp_instance}), and save to(@{get_ftp_list})
    icon: get-folder
    helpManual: Get all file/folder list under specified FTP connection
    inputList:
    - key: ftp_instance
      title: FTP Connection Object
      tip: FTP connection object to get file and folder information
    - key: file_type
      title: Get Object
      tip: Select object to get
    outputList:
    - key: get_ftp_list
      title: Obtained File/Folder List
      tip: Output file/folder list under FTP connection to variable
  Network.ftp_rename:
    title: Rename File/Folder (FTP)
    comment: Rename (@{file_type})(@{cur_file_name||cur_folder_name}) in(@{ftp_instance}) to new name(@{new_file_name||new_folder_name}), and save renamed path to variable(@{rename_ftp_path})
    icon: rename-folder
    helpManual: Rename file/folder on FTP server
    inputList:
    - key: ftp_instance
      title: FTP Connection Object
      tip: FTP connection object to perform file/folder rename operation
    - key: file_type
      title: Rename Object
      tip: ''
    - key: cur_file_name
      title: Original File Name
      tip: Enter file to rename
    - key: new_file_name
      title: New File Name (excluding file extension)
      tip: Enter new file name, excluding file extension
    - key: cur_folder_name
      title: Original Folder Name
      tip: Enter folder to rename
    - key: new_folder_name
      title: New Folder Name
      tip: Enter new folder name
    - key: exist_type
      title: When Renamed Object Exists
      tip: Operation to perform when renamed object already exists
    outputList:
    - key: rename_ftp_path
      title: Renamed Path
      tip: Save renamed (@{file_type}) path to variable
  Network.ftp_upload:
    title: Upload File/Folder (FTP)
    comment: Upload (@{file_path||folder_path}) to FTP specified directory(@{ftp_pwd}), and save uploaded path result to(@{upload_ftp_list})
    icon: upload-folder
    helpManual: Upload one or more local files/folders to FTP specified directory
    inputList:
    - key: ftp_instance
      title: FTP Connection Object
      tip: FTP connection object to upload file/folder
    - key: file_type
      title: Upload Object
      tip: ''
    - key: ftp_pwd
      title: Remote Working Directory
      tip: Remote working directory for file/folder upload, default is empty, uploads to current working path
    - key: file_path
      title: File to Upload
      tip: Supports single or multiple file upload, multiple file names separated by comma, e.g.:test1.txt,test2.txt,test3.txt
    - key: folder_path
      title: Folder to Upload
      tip: Supports single or multiple folder upload, multiple folders separated by comma, e.g.:folder1,folder2,folder3
    - key: exist_type
      title: When Upload Object Already Exists
      tip: Handling method when file/folder to upload already exists on FTP server
    outputList:
    - key: upload_ftp_list
      title: Upload List
      tip: Output uploaded file/folder path information on FTP server to variable, data type is list
  Network.ftp_download:
    title: Download File/Folder (FTP)
    comment: Download (@{download_file_name||download_folder_name}) to local directory(@{dst_path}), and save downloaded path to variable(@{download_ftp_path})
    icon: download-folder
    helpManual: Download multiple files/folders from FTP server to local
    inputList:
    - key: ftp_instance
      title: FTP Connection Object
      tip: FTP server connection object to perform download file/folder
    - key: file_type
      title: Download Object
      tip: ''
    - key: download_file_name
      title: File to Download
      tip: Supports single or multiple file download, multiple file names separated by comma, e.g.:test1.txt,test2.txt,test3.txt
    - key: download_folder_name
      title: Folder to Download
      tip: Supports single or multiple folder download, multiple folders separated by comma, e.g.:folder1,folder2,folder3
    - key: dst_path
      title: Download to
      tip: Local storage path
    - key: state_type
      title: When Local Path Does Not Exist
      tip: Operation to perform when local storage path does not exist
    - key: exist_type
      title: When Download Object Exists
      tip: Operation to perform when downloaded file/folder exists
    outputList:
    - key: download_ftp_path
      title: Download List
      tip: Output downloaded file/folder path list to variable, data type is list
  Network.ftp_delete:
    title: Delete File/Folder (FTP)
    comment: Delete (@{delete_file_name||delete_folder_name}) on(@{ftp_instance}), and output delete result to variable(@{delete_ftp_result})
    icon: delete-folder-ftp
    helpManual: Delete specified file/folder in FTP server
    inputList:
    - key: ftp_instance
      title: FTP Connection Object
      tip: FTP connection object to perform file/folder delete operation
    - key: file_type
      title: Delete Object
      tip: ''
    - key: delete_file_name
      title: File to Delete
      tip: Supports single or multiple file deletion, multiple file names separated by comma, e.g.:test1.txt,test2.txt,test3.txt
    - key: delete_folder_name
      title: Folder to Delete
      tip: Supports single or multiple folder deletion, multiple folders separated by comma, e.g.:folder1,folder2,folder3
    outputList:
    - key: delete_ftp_result
      title: Delete Result
      tip: Output delete result to variable, data type is boolean
options:
  RequestType:
  - value: post
    label: post
  - value: get
    label: get
  - value: connect
    label: connect
  - value: put
    label: put
  - value: patch
    label: patch
  - value: delete
    label: delete
  - value: options
    label: options
  - value: head
    label: head
  - value: trace
    label: trace
  SaveType:
  - value: 'yes'
    label: Save
  - value: 'no'
    label: Delete
  StateType:
  - value: create
    label: Create
  - value: error
    label: Prompt and Report Error
  FileExistenceType:
  - value: overwrite
    label: Overwrite Existing File
  - value: rename
    label: Create File Copy
  - value: cancel
    label: Cancel Save Operation
  ListType:
  - value: all
    label: All
  - value: file
    label: File
  - value: folder
    label: Folder
  FileType:
  - value: file
    label: File
  - value: folder
    label: Folder
