atomic:
  Enterprise.upload_to_sharefolder:
    title: Upload File to Shared Folder
    comment: Upload file @{file_path}, return upload result @{upload_result}
    icon: ''
    helpManual: ''
    inputList:
    - key: file_path
      title: Upload File Path
      tip: ''
    outputList:
    - key: upload_result
      title: Upload File Result
      tip: ''
  Enterprise.download_from_sharefolder:
    title: Download File from Shared Folder
    comment: Download file @{file_path} to @{save_folder}, return download result @{download_result}
    icon: ''
    helpManual: ''
    inputList:
    - key: file_path
      title: Shared Folder File
      tip: ''
    - key: save_folder
      title: File Save Path
      tip: ''
    outputList:
    - key: download_result
      title: Download Result
      tip: ''
  Enterprise.get_shared_variable:
    title: Get Shared Variable
    comment: Get Shared Variable @{shared_variable} to variable @{variable_data}
    icon: get-shared-variable
    helpManual: ''
    inputList:
    - key: shared_variable
      title: Shared Variable Name
      tip: Select the shared variable to get
    outputList:
    - key: variable_data
      title: Save Shared Variable To
      tip: ''
options: {}
