atomic:
  OpenApi.id_card:
    title: ID Card Recognition
    comment: ID Card Recognition
    icon: id-card-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: Batch Processing
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially
    - key: src_file
      title: Image File
      tip: ''
    - key: src_dir
      title: Image Folder
      tip: ''
    - key: is_save
      title: Output Document
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially, saves as Excel document by default, modification not supported
    - key: dst_file
      title: Document Output Path
      tip: ''
    - key: dst_file_name
      title: Document Output File Name
      tip: selectDocument Output File Name
    outputList:
    - key: id_card
      title: ID Card Recognition Result Object
      tip: Output ID card recognition result
  OpenApi.business_license:
    title: Business License Recognition
    comment: Business License Recognition
    icon: business-license-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: Batch Processing
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially
    - key: src_file
      title: Image File
      tip: ''
    - key: src_dir
      title: Image Folder
      tip: ''
    - key: is_save
      title: Output Document
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially, saves as Excel document by default, modification not supported
    - key: dst_file
      title: Document Output Path
      tip: ''
    - key: dst_file_name
      title: Document Output File Name
      tip: Select document output file name
    outputList:
    - key: business_license
      title: Business License Result Object
      tip: Output business license result object
  OpenApi.vat_invoice:
    title: VAT Invoice Recognition
    comment: VAT Invoice Recognition
    icon: vat-invoice-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: Batch Processing
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially
    - key: src_file
      title: Image File
      tip: ''
    - key: src_dir
      title: Image Folder
      tip: ''
    - key: is_save
      title: Output Document
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially, saves as Excel document by default, modification not supported
    - key: dst_file
      title: Document Output Path
      tip: ''
    - key: dst_file_name
      title: Document Output File Name
      tip: Select document output file name
    outputList:
    - key: vat_invoice
      title: VAT Invoice Recognition Result Object
      tip: Output VAT invoice recognition result object
  OpenApi.train_ticket:
    title: Train Ticket Recognition
    comment: Train Ticket Recognition
    icon: train-ticket-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: Batch Processing
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially
    - key: src_file
      title: Image File
      tip: ''
    - key: src_dir
      title: Image Folder
      tip: ''
    - key: is_save
      title: Output Document
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially, saves as Excel document by default, modification not supported
    - key: dst_file
      title: Document Output Path
      tip: ''
    - key: dst_file_name
      title: Document Output File Name
      tip: Select document output file name
    outputList:
    - key: train_ticket
      title: Train Ticket Recognition Result Object
      tip: Train ticket recognition result object
  OpenApi.taxi_ticket:
    title: Taxi Invoice Recognition
    comment: Taxi Invoice Recognition
    icon: taxi-invoice-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: Batch Processing
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially
    - key: src_file
      title: Image File
      tip: ''
    - key: src_dir
      title: Image Folder
      tip: ''
    - key: is_save
      title: Output Document
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially, saves as Excel document by default, modification not supported
    - key: dst_file
      title: Document Output Path
      tip: ''
    - key: dst_file_name
      title: Document Output File Name
      tip: Select document output file name
    outputList:
    - key: taxi_ticket
      title: Taxi Invoice Recognition Result Object
      tip: Taxi invoice recognition result object
  OpenApi.common_ocr:
    title: General Text Recognition
    comment: General Text Recognition
    icon: general-text-recognition
    helpManual: ''
    inputList:
    - key: is_multi
      title: Batch Processing
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially
    - key: src_file
      title: Image File
      tip: ''
    - key: src_dir
      title: Image Folder
      tip: ''
    - key: is_save
      title: Output Document
      tip: Select 'No' to process one image file each time, select 'Yes' to process all files in folder sequentially, saves as Excel document by default, modification not supported
    - key: dst_file
      title: Document Output Path
      tip: Select document output folder
    - key: dst_file_name
      title: Document Output File Name
      tip: Select document output file name
    outputList:
    - key: common_ocr
      title: General Text Recognition Result Object
      tip: Output general text recognition result object
options:
  Bool:
  - value: true
    label: 'Yes'
  - value: false
    label: 'No'
